#!/bin/sh

set -uo pipefail

intercrash_sleep=10

while true; do
  ./server-input | java -Xmx1024M -Xms1024M -jar minecraft-server.jar nogui | ./server-output
  echo "Server crashed!  Will restart in $intercrash_sleep seconds"
  sleep $intercrash_sleep
done
