#!/usr/bin/ruby

def docmd( line )
  STDERR.puts "Server input generator: Doing #{line}"
  STDOUT.puts line
  STDOUT.flush
end

t = Thread.new {
  sleep 20 # Give the server time to start
  loop {
    sleep 600
    docmd "/list"
    docmd "/save-off"
    docmd "/save-all"
    sleep 60
    docmd "/save-on"
  }
}

while line = gets
  line = line.strip
  unless line.empty?
    if line == 'force-save'
      docmd "/say Please update despite lack of players."
      docmd "/save-off"
      docmd "/save-all"
      STDERR.puts "Dear user: please /save-on when done."
    else
      STDOUT.puts line
      STDOUT.flush
    end
    if line == 'stop' or line == '/stop'
      break
    end
  end
end
t.kill
