#!/usr/bin/ruby

#[19:36:34] [Server thread/INFO]: There are 0/20 players online:
#[19:36:34] [Server thread/INFO]:
#/save-off
#[19:47:39] [Server thread/INFO]: Turned off world auto-saving
#/save-all
#[19:47:42] [Server thread/INFO]: Saving...
#[19:47:42] [Server thread/INFO]: Saved the world
#/save-on
#[19:47:51] [Server thread/INFO]: Turned on world auto-saving
#/list
#[19:48:13] [Server thread/INFO]: There are 0/20 players online:
#[19:48:13] [Server thread/INFO]: 

$verbosity = 1

def log(triviality, msg)
  return if triviality > $verbosity
  
  puts "Server output monitor: #{msg}"
end

def sys(stuff)
  log 1, "$ #{stuff}"
  system(stuff)
  log 1, "Command exited with status #{$?.exitstatus}"
end

if File.read('server.properties') =~ /^level-name=(.*)$/
  $world_dir = $1
else
  STDERR.puts "Couldn't find level-name in server.properties."
  exit 1
end

log 1, "World dir: '#{$world_dir}'"

$autosaving = true
$world_saved_since_autosaving_disabled
$players_online_since_last_backup = false
$onlin
while line = gets
  # Ignore 'unknown command' lines
  #next if line =~ %r<\[Server thread/INFO\]: Unknown command.>

  print line
  if line =~ %r<\[Server thread/INFO\]: Turned (on|off) world auto-saving>
    $autosaving = $1 == 'on'
    $world_saved_since_autosaving_disabled = false
    log 2, "Server output monitor: Auto-saving's #{$1}!"
  elsif line =~ %r<\[Server thread/INFO\]: (.*) (joined|left) the game>
    $players_online_since_last_backup = true
  elsif line =~ %r<\[Server thread/INFO\]: \[Server\] Please update despite lack of players.>
    log 1, "Will pretend players have been online."
    $players_online_since_last_backup = true
  elsif line =~ %r<\[Server thread/INFO\]: Saved the world>
    log 2, "World saved."
    if $autosaving == false
      log 2, "Autosaving is off."
      $world_saved_since_autosaving_disabled = true
      if $players_online_since_last_backup
        $players_online_since_last_backup = false
        log 2, "There were players online since the last backup."
        log 1, "Time to make a backup!  Waiting a few seconds so files can stabilize..."
        sleep 10
        sys "make -C '#{$world_dir}' update"
      else
        log 2, "But no players were online since last backup; taking no action."
      end
    else
      log 2, "But autosaving is still on; taking no action."
    end
  elsif line =~ %r<\[Server thread/INFO\]: There are (\d+)/(\d+) players online>
    if( $1.to_i > 0 )
      $players_online_since_last_backup = true
    end
  end
end
